### ISSUE TITLE
Django 1.4

### ISSUE THREAD

**Issue by jnbek** [ckelly/django-resume#1]
Any plans to update this for the 1.4 version? Installing this on 1.4 causes a fatal warning about deprecated template functions.

**Comment by aless80** [comment]
Hi,
I'm afraid it is broken again. 


kinkyboy python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7f41ea13e230>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kinkyboy/django-resume/django_resume/resume/models.py", line 70, in <module>
    class Job(models.Model):
  File "/home/kinkyboy/django-resume/django_resume/resume/models.py", line 74, in Job
    company_url = models.URLField('Company URL', verify_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 2283, in __init__
    super(URLField, self).__init__(verbose_name, name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1043, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'verify_exists'
kinkyboy pip show django
---
Name: Django
Version: 1.10.1
Location: /usr/local/lib/python2.7/dist-packages
Requires:

**Comment by ckelly** [comment]
hi @aless80 I will try and take a look over the next week or so. I will welcome PRs as well if you get to it first :)

**Comment by aless80** [comment]
Hello,
I am a beginner in django but i started fixing it until I decided to recreate the project from scratch.. It is starting to work, but not completely, see here

https://github.com/aless80/Djangoresume/tree/master
